### ISSUE TITLE
Subdivision tiers

### ISSUE THREAD

**Issue by madshargreave** [countries/countries#186]
Hey

This page http://en.wikipedia.org/wiki/ISO_3166-2:GB specifies subdivision names as listed in the ISO 3166-2 standard

There are 4 codes ENG, NIR, SCT and WL (England, Northern Ireland, Scotland and Wales) that are higher tiered than what the gem currently returns as UK subdivisions.

This means that we have different tiers of subdivisions, where the gem currently only supports the lowest level

Will you be able to implement this, and if not, do you prefer an approach that we could take and submit a pull request?

Much appreciated
- Mads

**Comment by rposborne** [comment]
I think something along these lines would be fantastic, but need some thought about the structure.   Similar to the way Google uses the "Administrative_level 1-8" in their addresses.

**Comment by rposborne** [comment]
Here is a nice break down from Open Street Map, http://wiki.openstreetmap.org/wiki/Tag:boundary%3Dadministrative

**Comment by rposborne** [comment]
Here are my thoughts for overall structure. 
``` yaml
administrative_level_1:
  name: region
  divisions: 
    CE:
      name: Central
      names: Central
      translations:
        en: Central
    GH:
      name: Ghanzi
      names:
      - Ghansi
      - Khanzi
```

This would be accompanied by a ```sub_division_catagories.yml``` file which would hold options of sub_divison names and their respective translations.

**Comment by noyg** [comment]
Will this feature be developed?

**Comment by rposborne** [comment]
Some more resources from wikipedia https://en.wikipedia.org/wiki/List_of_administrative_divisions_by_country, 

@noyg This is up on the list, but it's a pretty big lift, I am more than happy to bring other people in to help get it done if you have the time.

**Comment by rposborne** [comment]
So putting a bit more of thought into this, I think for simplicities sake we can drop the `catagories.yml` file 

``` yaml
administrative_level_1:
  translations:
    en: 'Region'
    cz: 'kraj'
  divisions: 
    CE:
      translations:
        en: Central
    GH:
      translations:
        en: Central
```

I also want to strip out `name` and `names`, as its very redundant to the translations.
