### ISSUE TITLE
Implement cities support

### ISSUE THREAD

**Issue by KieranP** [countries/countries#254]
It would be very useful to implement cities support, even if very slim. It could derive data from two existing databases: MaxMind GeoLite and GeoLite2. Namely these two files:

http://geolite.maxmind.com/download/geoip/database/GeoLite2-City-CSV.zip
(contains city name, country iso code, time zone)

http://geolite.maxmind.com/download/geoip/database/GeoLiteCity_CSV/GeoLiteCity-latest.zip
(contains city name, country iso code, longitude, latitude)

A script could be created to parse the CSV files and generate a cities YAML file for each country in the format of:

``` yaml

---
NZ:
  cities:
    -
      name: Wellington
      latitude: -41.3
      longitude: 174.783333
      timezone: "Pacific/Auckland"
```

Desired API usage:

``` ruby
country = ISO3166::Country["NZ"]
country.cities => [#<ISO3166::City>, ...]
city = country.cities[0]
city.name => "Wellington"
city.latitude => -41.3
city.longitude => 174.783333
city.timezone => "Pacific/Auckland"
```
