### ISSUE TITLE
typo, countries.yaml

### ISSUE THREAD

**Issue by ghost** [countries/countries#37]
Typo in [countries.yaml](https://github.com/hexorx/countries/blob/master/lib/data/countries.yaml) file, _langauges_ insted of _languages_.

```
FO: 
  alpha2: FO
  alpha3: FRO
  langauges:
    - fo
```
