### ISSUE TITLE
Change continent name from Australia to Oceania and add continent code

### ISSUE THREAD

**Issue by Yu-Jack** [countries/countries#700]
According to this [PR#32](https://github.com/countries/countries/pull/32) mentions this dataset [dev.maxmind.com - iso-3166-country-codes-with-associated-continent](https://dev.maxmind.com/geoip/legacy/codes?lang=en#iso-3166-country-codes-with-associated-continent), there is no continent code for Australia, but for Oceania now.

Is it okay to change Australia to Oceania and add continent code? like below example.

Current
```
NR:
  continent: Australia
  alpha2: NR
  alpha3: NRU
```

Expected
```
NR:
  continent: Oceania
  continent_code: OC
  alpha2: NR
  alpha3: NRU
```

But, consider the downward compatible, we maybe can add prefix like this.
```
NR:
  continent: Australia
  formal_continent: Oceania
  formal_continent_code: OC
  alpha2: NR
  alpha3: NRU
```
